import io, re, sys

html = io.open('.output/public/en/cities/guizhou/index.html', encoding='utf-8').read()
title = re.search(r'<title>([^<]+)</title>', html)
print('title:', title.group(1) if title else 'MISSING')
print('h1 Guizhou:', 'Guizhou' in html)
print('Huangguoshu count:', html.count('Huangguoshu'))
print('Fanjingshan count:', html.count('Fanjingshan'))
print('highest bridge phrase:', html.count('highest bridge'))
print('bilibili vlog links:', html.count('bilibili.com/video'))
print('TouristDestination JSON-LD:', 'TouristDestination' in html)
print('hreflang links:', html.count('hreflang'))
print('canonical:', 'rel="canonical"' in html)
print('guizhou images:', html.count('/images/cities/guizhou/'))
print('vlog covers:', html.count('/images/vlogs/'))
print('guide links wikivoyage:', 'wikivoyage' in html)
# zh page check
zh = io.open('.output/public/zh/cities/guizhou/index.html', encoding='utf-8').read()
print('zh 黄果树:', zh.count('黄果树') > 3)
print('zh 梵净山:', '梵净山' in zh)
print('zh vlog links:', zh.count('bilibili.com/video'))
# ko fallback check (should fall back to EN content)
ko = io.open('.output/public/ko/cities/guizhou/index.html', encoding='utf-8').read()
print('ko page exists, has Huangguoshu (EN fallback):', 'Huangguoshu' in ko)
